### ISSUE TITLE
requesting an icon

### ISSUE THREAD

**Issue by Best-Verie** [stunicons/stunicons#10]
I personally liked ur icons fr u did a great job.
in addition to different icons found so far on the site, I would like to request for a twitter and github icon.

**Comment by aimelyse** [comment]
Yeah, sure we put that in considerations,
Keep enjoying Stunicons !

**Comment by claranceliberi** [comment]
@Best-Verie we now have that icon, with our new latest release

**Comment by Best-Verie** [comment]
Thanks team
