### ISSUE TITLE
dollar-sign icon request

### ISSUE THREAD

**Issue by divinirakiza** [stunicons/stunicons#12]
Would like to request an icon to use in my [rfid-octo](https://github.com/users/DivinIrakiza/projects/2)

- icon name: dollar-sign

 Here is a preview
![money-dollar-circle-line (1)](https://user-images.githubusercontent.com/52403928/117398396-92a2c880-aefe-11eb-8576-06f5dc9757e0.png)

**Comment by claranceliberi** [comment]
@divinirakiza we now have that icon on our latest release
